name: indonesia_student_case
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - aom=3.5.0
  - blosc=1.21.4
  - bokeh=3.1.1
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-blosc2=2.8.0
  - ca-certificates=2023.08.22
  - cairo=1.16.0
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contourpy=1.0.7
  - curl=8.1.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.5.0
  - dav1d=1.2.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.5.0
  - geojson=3.0.1
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - importlib-resources=5.12.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jxrlib=1.1
  - kealib=1.5.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.1.1
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.6.4
  - libglib=2.76.3
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libpng=1.6.39
  - libpq=15.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.10.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib-base=3.7.1
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - openjpeg=2.5.0
  - openssl=3.1.0
  - pandas=1.5.3
  - partd=1.4.0
  - pcre2=10.40
  - pip=23.0.1
  - pixman=0.40.0
  - pooch=1.7.0
  - poppler=23.04.0
  - poppler-data=0.4.12
  - postgresql=15.3
  - proj=9.2.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pywavelets=1.4.1
  - pyyaml=6.0
  - setuptools=67.6.0
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlite=3.41.2
  - tbb=2021.9.0
  - tiledb=2.13.2
  - tk=8.6.12
  - toolz=0.12.0
  - ucrt=10.0.22621.0
  - unicodedata2=15.0.0
  - vc=14.3
  - vc14_runtime=14.34.31931
  - vs2015_runtime=14.34.31931
  - wheel=0.40.0
  - win_inet_pton=1.1.0
  - xarray=2023.1.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - access==1.1.9
    - alabaster==0.7.13
    - anyio==3.7.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - astroid==2.15.1
    - asttokens==2.2.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - atomicwrites==1.4.1
    - attrs==22.2.0
    - autopep8==1.6.0
    - babel==2.12.1
    - backcall==0.2.0
    - bcrypt==4.0.1
    - beautifulsoup4==4.12.0
    - binaryornot==0.4.4
    - black==23.1.0
    - bleach==6.0.0
    - cachetools==5.3.0
    - cdsapi==0.6.1
    - certifi==2022.12.7
    - cffi==1.15.1
    - cftime==1.6.2
    - chardet==5.1.0
    - comm==0.1.3
    - cookiecutter==2.1.1
    - cryptography==40.0.1
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - diff-match-patch==20200713
    - dill==0.3.6
    - docstring-to-markdown==0.12
    - docutils==0.19
    - entrypoints==0.4
    - esda==2.4.3
    - exceptiongroup==1.1.2
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - fiona==1.9.4.post1
    - flake8==6.0.0
    - flatbuffers==23.3.3
    - fonttools==4.39.2
    - fqdn==1.5.1
    - gast==0.4.0
    - geopandas==0.13.2
    - giddy==2.3.4
    - google-auth==2.16.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.53.0
    - h5py==3.8.0
    - imageio==2.27.0
    - imagesize==1.4.1
    - importlib-metadata==6.1.0
    - inequality==1.0.0
    - inflection==0.5.1
    - intervaltree==3.1.0
    - ipykernel==6.22.0
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.0
    - isoduration==20.11.0
    - isort==5.12.0
    - jaraco-classes==3.2.3
    - jax==0.4.7
    - jedi==0.18.2
    - jellyfish==0.11.0
    - jinja2-time==0.2.0
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==7.4.9
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.24.0
    - jupyterlab-widgets==3.0.8
    - keras==2.12.0
    - keyring==23.13.1
    - lazy-loader==0.2
    - lazy-object-proxy==1.9.0
    - libclang==16.0.0
    - libpysal==4.7.0
    - llvmlite==0.39.1
    - mapclassify==2.6.0
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mgwr==2.1.2
    - mistune==2.0.5
    - ml-dtypes==0.0.4
    - momepy==0.6.0
    - more-itertools==9.1.0
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - nbclient==0.7.2
    - nbconvert==7.2.10
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - netcdf4==1.6.4
    - networkx==3.0
    - notebook==7.0.2
    - notebook-shim==0.2.3
    - numba==0.56.4
    - numpy==1.23.5
    - numpydoc==1.5.0
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - overrides==7.4.0
    - packaging==23.0
    - pandocfilters==1.5.0
    - paramiko==3.1.0
    - parso==0.8.3
    - pathspec==0.11.1
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.2.0
    - pluggy==1.0.0
    - pointpats==2.3.0
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.38
    - protobuf==4.22.1
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pulp==2.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.10.0
    - pycparser==2.21
    - pydocstyle==6.2.3
    - pyflakes==3.0.1
    - pygeos==0.14
    - pygments==2.14.0
    - pylint==2.17.1
    - pylint-venv==3.0.1
    - pyls-spyder==0.4.0
    - pynacl==1.5.0
    - pyproj==3.4.1
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - pyqtwebengine==5.15.6
    - pyqtwebengine-qt5==5.15.2
    - pyreadstat==1.2.3
    - pyrsistent==0.19.3
    - pysal==23.7
    - pysheds==0.3.3
    - python-json-logger==2.0.7
    - python-lsp-black==1.2.1
    - python-lsp-jsonrpc==1.0.0
    - python-lsp-server==1.7.1
    - python-slugify==8.0.1
    - pytoolconfig==1.2.5
    - pytz==2023.2
    - pywin32==306
    - pywin32-ctypes==0.2.0
    - pywinpty==2.0.11
    - pyzmq==25.0.2
    - qdarkstyle==3.0.3
    - qstylizer==0.2.2
    - qtawesome==1.2.3
    - qtconsole==5.4.1
    - qtpy==2.3.0
    - quantecon==0.7.1
    - rasterio==1.3.6
    - rasterstats==0.19.0
    - referencing==0.30.2
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rioxarray==0.13.4
    - rope==1.7.0
    - rpds-py==0.9.2
    - rsa==4.9
    - rtree==1.0.1
    - scikit-image==0.20.0
    - scikit-learn==1.3.0
    - scipy==1.9.1
    - seaborn==0.12.2
    - segregation==2.4.2
    - send2trash==1.8.2
    - shapely==2.0.1
    - simplejson==3.19.1
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4
    - spaghetti==1.7.4
    - spglm==1.0.8
    - sphinx==6.1.3
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - spint==1.0.7
    - splot==1.1.5.post1
    - spopt==0.5.0
    - spreg==1.3.2
    - spvcm==0.3.0
    - spyder==5.4.2
    - spyder-kernels==2.4.2
    - stack-data==0.6.2
    - statsmodels==0.14.0
    - sympy==1.12
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-intel==2.12.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - terminado==0.17.1
    - text-unidecode==1.3
    - textdistance==4.5.0
    - threadpoolctl==3.2.0
    - three-merge==0.1.1
    - tifffile==2023.3.21
    - tinycss2==1.2.1
    - tobler==0.9.0
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.7
    - tornado==6.2
    - tqdm==4.66.0
    - traitlets==5.9.0
    - typing-extensions==4.5.0
    - ujson==5.7.0
    - uri-template==1.3.0
    - urllib3==1.26.15
    - watchdog==3.0.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.1
    - werkzeug==2.2.3
    - whatthepatch==1.0.4
    - widgetsnbextension==4.0.8
    - wrapt==1.14.1
    - yapf==0.32.0
