name: indonesia_student_case
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=3
  - geojson=3
  - pandas=1
  - pip=23
  - python=3.8
  - xarray=2023.1.0
  - matplotlib-base=3.7
  - pip:
    - geopandas==0.13
    - matplotlib-inline==0.1
    - netcdf4==1.6
    - notebook==7.0
    - numpy==1.23
    - rasterio==1.3
    - pysheds==0.3
  